// ---- Created with 3Dmigoto v1.4.1 on Fri Feb 20 11:57:18 2026

cbuffer _Globals : register(b0)
{
  float4x4 ScreenToWorldMatrix : packoffset(c0);
  float4 SpherePositionRadius : packoffset(c4);
  bool bDecompressSceneColor : packoffset(c5);
  float4 SampleOffsets[8] : packoffset(c6);
  float3 ShadowBufferSizeAndSoftTransitionScale : packoffset(c14);
  float2 ShadowTexelSize : packoffset(c15);
  float LightingChannelMask : packoffset(c15.z);
  float MinShadowOpacity : packoffset(c15.w);
  float ShadowFadeFraction : packoffset(c16);
  float4x4 StaticScreenToShadowMatrix : packoffset(c17);
  float4x4 DynamicScreenToShadowMatrix : packoffset(c21);
  float4 LightPositionAndInvRadius : packoffset(c25);
  float4x4 ShadowViewProjectionMatrices[6] : packoffset(c26);
  float ShadowmapResolution : packoffset(c50);
}

cbuffer PSOffsetConstants : register(b2)
{
  float4 ScreenPositionScaleBias : packoffset(c0);
  float4 MinZ_MaxZRatio : packoffset(c1);
  float NvStereoEnabled : packoffset(c2);
  float4 DiffuseOverrideParameter : packoffset(c3);
  float4 SpecularOverrideParameter : packoffset(c4);
  float4 CameraPositionPS : packoffset(c5);
  float4 ScreenTexelSize : packoffset(c6);
  float4 ViewportPositionScaleBias : packoffset(c7);
  float4 TransLightingVolumeMin : packoffset(c8);
  float4 TransLightingVolumeInvSize : packoffset(c9);
  float2 NumMSAASamples : packoffset(c10);
}

SamplerState SceneDepthTexture_s : register(s0);
SamplerState StaticShadowDepthTexture_s : register(s1);
SamplerState DynamicShadowDepthTexture_s : register(s2);
Texture2D<float4> SceneDepthTexture : register(t0);
Texture2D<float4> StaticShadowDepthTexture : register(t1);
Texture2D<float4> DynamicShadowDepthTexture : register(t2);


// 3Dmigoto declarations
#define cmp -


void main(
  float4 v0 : TEXCOORD0,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1,r2,r3,r4,r5,r6,r7,r8,r9;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xy = v0.xy / v0.ww;
  r0.zw = r0.xy * ScreenPositionScaleBias.xy + ScreenPositionScaleBias.wz;
  r0.z = SceneDepthTexture.SampleLevel(SceneDepthTexture_s, r0.zw, 0).x;
  r0.w = r0.z * MinZ_MaxZRatio.z + -MinZ_MaxZRatio.w;
  r0.z = cmp(0.999000013 < r0.z);
  r0.w = 1 / r0.w;
  r0.z = r0.z ? 1000000 : r0.w;
  r0.xy = r0.xy * r0.zz;
  r1.xyzw = StaticScreenToShadowMatrix._m01_m11_m21_m31 * r0.yyyy;
  r1.xyzw = StaticScreenToShadowMatrix._m00_m10_m20_m30 * r0.xxxx + r1.xyzw;
  r1.xyzw = StaticScreenToShadowMatrix._m02_m12_m22_m32 * r0.zzzz + r1.xyzw;
  r1.xyzw = StaticScreenToShadowMatrix._m03_m13_m23_m33 + r1.xyzw;
  r2.xyzw = r1.xyxy / r1.wwww;
  r0.w = min(0.999000013, r1.z);
  r1.xyzw = r2.xyzw * ShadowBufferSizeAndSoftTransitionScale.xyxy + float4(-2,-2,-2,-2);
  r2.xy = ShadowBufferSizeAndSoftTransitionScale.xy * r2.zw;
  r2.xy = frac(r2.xy);
  r1.xyzw = floor(r1.xyzw);
  r3.xyzw = float4(0.5,0.5,1.5,0.5) + r1.zwzw;
  r3.xyzw = ShadowTexelSize.xyxy * r3.xyzw;
  r3.z = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r3.zw, 0).x;
  r3.x = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r3.xy, 0).x;
  r3.x = r3.x + -r0.w;
  r4.x = saturate(r3.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r3.x = r3.z + -r0.w;
  r3.x = saturate(r3.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r5.xyzw = DynamicScreenToShadowMatrix._m01_m11_m21_m31 * r0.yyyy;
  r5.xyzw = DynamicScreenToShadowMatrix._m00_m10_m20_m30 * r0.xxxx + r5.xyzw;
  r5.xyzw = DynamicScreenToShadowMatrix._m02_m12_m22_m32 * r0.zzzz + r5.xyzw;
  r5.xyzw = DynamicScreenToShadowMatrix._m03_m13_m23_m33 + r5.xyzw;
  r6.xyzw = r5.xyxy / r5.wwww;
  r0.x = min(0.999000013, r5.z);
  r5.xyzw = r6.xyzw * ShadowBufferSizeAndSoftTransitionScale.xyxy + float4(-2,-2,-2,-2);
  r0.yz = ShadowBufferSizeAndSoftTransitionScale.xy * r6.zw;
  r2.zw = frac(r0.yz);
  r5.xyzw = floor(r5.xyzw);
  r6.xyzw = float4(0.5,0.5,1.5,0.5) + r5.zwzw;
  r6.xyzw = ShadowTexelSize.xyxy * r6.xyzw;
  r0.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r6.zw, 0).x;
  r0.z = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r6.xy, 0).x;
  r0.yz = r0.yz + -r0.xx;
  r4.y = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r3.y = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r6.xyzw = float4(2.5,0.5,3.5,0.5) + r1.zwzw;
  r6.xyzw = ShadowTexelSize.xyxy * r6.xyzw;
  r0.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r6.xy, 0).x;
  r0.z = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r6.zw, 0).x;
  r0.yz = r0.yz + -r0.ww;
  r6.x = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r7.x = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(2.5,0.5,3.5,0.5) + r5.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r0.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.xy, 0).x;
  r0.z = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.zw, 0).x;
  r0.yz = r0.yz + -r0.xx;
  r6.y = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r7.y = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(0.5,1.5,1.5,1.5) + r1.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r0.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.zw, 0).x;
  r0.z = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.xy, 0).x;
  r0.yz = r0.yz + -r0.ww;
  r4.z = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r3.z = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(0.5,1.5,1.5,1.5) + r5.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r0.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.zw, 0).x;
  r0.z = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.xy, 0).x;
  r0.yz = r0.yz + -r0.xx;
  r4.w = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r3.w = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(2.5,1.5,3.5,1.5) + r1.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r0.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.xy, 0).x;
  r0.z = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.zw, 0).x;
  r0.yz = r0.yz + -r0.ww;
  r6.z = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r7.z = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(2.5,1.5,3.5,1.5) + r5.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r0.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.xy, 0).x;
  r0.z = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.zw, 0).x;
  r0.yz = r0.yz + -r0.xx;
  r6.w = saturate(r0.z * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r7.w = saturate(r0.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = r7.xyzw + -r3.xyzw;
  r8.xyzw = r2.xzxz * r8.xyzw + r3.xyzw;
  r9.xyzw = -r4.xyzw + r3.xyzw;
  r9.xyzw = r2.xzxz * r9.xyzw + r4.xyzw;
  r0.yz = r8.zw + -r8.xy;
  r0.yz = r2.yw * r0.yz + r8.xy;
  r8.xy = r9.zw + -r9.xy;
  r8.xy = r2.yw * r8.xy + r9.xy;
  r0.yz = r8.xy + r0.yz;
  r8.xyzw = -r7.xyzw + r6.xyzw;
  r8.xyzw = r2.xzxz * r8.xyzw + r7.xyzw;
  r8.zw = r8.zw + -r8.xy;
  r8.xy = r2.yw * r8.zw + r8.xy;
  r0.yz = r8.xy + r0.yz;
  r8.xyzw = float4(0.5,2.5,1.5,2.5) + r1.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r8.x = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.xy, 0).x;
  r8.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.zw, 0).x;
  r8.xy = r8.xy + -r0.ww;
  r3.x = saturate(r8.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r4.x = saturate(r8.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(0.5,2.5,1.5,2.5) + r5.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r8.x = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.xy, 0).x;
  r8.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.zw, 0).x;
  r8.xy = r8.xy + -r0.xx;
  r3.y = saturate(r8.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r4.y = saturate(r8.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = -r4.zwxy + r3.zwxy;
  r8.xyzw = r2.xzxz * r8.xyzw + r4.zwxy;
  r8.zw = r8.zw + -r8.xy;
  r8.xy = r2.yw * r8.zw + r8.xy;
  r0.yz = r8.xy + r0.yz;
  r8.xyzw = float4(2.5,2.5,3.5,2.5) + r1.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r8.x = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.xy, 0).x;
  r8.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.zw, 0).x;
  r8.xy = r8.xy + -r0.ww;
  r6.x = saturate(r8.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r7.x = saturate(r8.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(2.5,2.5,3.5,2.5) + r5.zwzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r8.x = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.xy, 0).x;
  r8.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.zw, 0).x;
  r8.xy = r8.xy + -r0.xx;
  r6.y = saturate(r8.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r7.y = saturate(r8.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = r7.zwxy + -r3.zwxy;
  r8.xyzw = r2.xzxz * r8.xyzw + r3.zwxy;
  r8.zw = r8.zw + -r8.xy;
  r8.xy = r2.yw * r8.zw + r8.xy;
  r0.yz = r8.xy + r0.yz;
  r8.xyzw = -r7.zwxy + r6.zwxy;
  r8.xyzw = r2.xzxz * r8.xyzw + r7.zwxy;
  r8.zw = r8.zw + -r8.xy;
  r8.xy = r2.yw * r8.zw + r8.xy;
  r0.yz = r8.xy + r0.yz;
  r8.xyzw = float4(0.5,3.5,1.5,3.5) + r1.zwzw;
  r1.xyzw = float4(2.5,3.5,3.5,3.5) + r1.xyzw;
  r1.xyzw = ShadowTexelSize.xyxy * r1.xyzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r8.x = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.xy, 0).x;
  r8.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r8.zw, 0).x;
  r8.xy = r8.xy + -r0.ww;
  r3.z = saturate(r8.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r4.z = saturate(r8.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = float4(0.5,3.5,1.5,3.5) + r5.zwzw;
  r5.xyzw = float4(2.5,3.5,3.5,3.5) + r5.xyzw;
  r5.xyzw = ShadowTexelSize.xyxy * r5.xyzw;
  r8.xyzw = ShadowTexelSize.xyxy * r8.xyzw;
  r8.x = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.xy, 0).x;
  r8.y = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r8.zw, 0).x;
  r8.xy = r8.xy + -r0.xx;
  r3.w = saturate(r8.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r4.w = saturate(r8.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r8.xyzw = -r4.xyzw + r3.xyzw;
  r4.xyzw = r2.xzxz * r8.xyzw + r4.xyzw;
  r4.zw = r4.zw + -r4.xy;
  r4.xy = r2.yw * r4.zw + r4.xy;
  r0.yz = r4.xy + r0.yz;
  r1.x = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r1.xy, 0).x;
  r1.y = StaticShadowDepthTexture.SampleLevel(StaticShadowDepthTexture_s, r1.zw, 0).x;
  r1.y = r1.y + -r0.w;
  r0.w = r1.x + -r0.w;
  r7.z = saturate(r0.w * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r6.z = saturate(r1.y * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r0.w = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r5.xy, 0).x;
  r1.x = DynamicShadowDepthTexture.SampleLevel(DynamicShadowDepthTexture_s, r5.zw, 0).x;
  r1.x = r1.x + -r0.x;
  r0.x = r0.w + -r0.x;
  r7.w = saturate(r0.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r6.w = saturate(r1.x * ShadowBufferSizeAndSoftTransitionScale.z + 1);
  r1.xyzw = -r7.xyzw + r6.xyzw;
  r1.xyzw = r2.xzxz * r1.xyzw + r7.xyzw;
  r4.xyzw = r7.xyzw + -r3.xyzw;
  r3.xyzw = r2.xzxz * r4.xyzw + r3.xyzw;
  r0.xw = r3.zw + -r3.xy;
  r0.xw = r2.yw * r0.xw + r3.xy;
  r0.xy = r0.yz + r0.xw;
  r0.zw = r1.zw + -r1.xy;
  r0.zw = r2.yw * r0.zw + r1.xy;
  r0.xy = r0.xy + r0.zw;
  r0.xy = saturate(float2(0.111110002,0.111110002) * r0.xy);
  r0.x = min(r0.x, r0.y);
  r0.y = 1 + -MinShadowOpacity;
  r0.x = r0.x * r0.y + MinShadowOpacity;
  r0.x = r0.x * r0.x + -1;
  r0.x = ShadowFadeFraction * r0.x + 1;
  o0.xyzw = sqrt(r0.xxxx);
  return;
}